remote_theme: pages-themes/minimal@v0.2.0
title: "Solving grub rescue and more"
description: "the1Riddles documentary"
permalinks: pretty
lang: en

# Navbar
navbar_link_text: "Error: no such partition, grub rescue"
navbar_button_text: "Send-Html_Form-to-Spreadsheet"
navbar_button_text: "This page on GitHub"
