theme: minimal
title: "How to fix 'no such partition, entering rescue mode..' error"
description: "Solving grub rescue"
permalinks: pretty
lang: en

# Navbar
navbar_link_text: "Error: no such partition, grub rescue"
navbar_button_text: "This page on GitHub"
